### PR TITLE
add support for deprecated directive in schema

### PR DESCRIPTION
**Pull request by jbwheatley**
see #19 
confirms to http://spec.graphql.org/June2018/#sec--deprecated

### CODE REVIEW

**Comment by milessabin** [comment]
This is more great stuff ... thanks!

I think the only thing missing is a test that deprecation is visible via schema introspection. Would you like to take a swing at adding a test along those lines?

**Comment by jbwheatley** [comment]
Yep, I can do that!

**Comment by jbwheatley** [comment]
@milessabin looks like there's already some testing around deprecation in introspection https://github.com/gemini-hlsw/gsp-graphql/blob/63c5ec1dfc6e1bab079f6c4b85b67e8319c56f30/modules/core/src/test/scala/introspection/IntrospectionSpec.scala#L704

**Comment by milessabin** [comment]
@jbwheatley Yup, but that's vai a manually constructed schema value with a deprecated. It'd be nice to have something that started from SDL as well. Or maybe instead? Perhaps replace the manually constucted schemas in those tests with SDL?

**Comment by milessabin** [comment]
But, actually, that could just as well be a follow on PR ... I think this is good to go as it is :smile:

**Pull request merged**
