### PR TITLE
Cross-build for Scala.js

### PR DESCRIPTION
**Pull request by jf-botto**
Solves #202.

Just made a draft PR to get some opinions. I still want to rearrange/reformat a few things so that there's as fewer changes possible.

I'm very confused as to why: sbt compile; test works. It seems to be running all the tests and they all pass. I don't understand why.

### CODE REVIEW

**Comment by armanbilge** [comment]
https://youforgotapercentagesignoracolon.com/

You need to change all the dependencies to use `%%`, not `%%%`. The results can be completely misleading otherwise (tooling issues...).

**Comment by jbotto94** [comment]
> https://youforgotapercentagesignoracolon.com/
> 
> You need to change all the dependencies to use `%%%`, not `%%`. The results can be completely misleading otherwise (tooling issues...).

Thank you so much!
I think the first issue I'm getting would actually be solved by getting Typename to compile to Scala.js, which I've noticed you have done herehttps://github.com/tpolecat/typename/pull/9...

**Comment by armanbilge** [comment]
@jbotto94 this is now unblocked if you are motivated to keep working on it :)

**Comment by jbotto94** [comment]
Will see what I can do

**Comment by milessabin** [comment]
I've just merged that typename update :smile:

**Comment by armanbilge** [comment]
Thank you for the early investigation! This landed in https://github.com/gemini-hlsw/gsp-graphql/pull/409.

**Pull request closed without merging**
