### PR TITLE
WIP: skunk support

### PR DESCRIPTION
**Pull request by tpolecat**
This adds the following:

- `modules/sql`, which contains the logic `doobiemapping.scala`, with the doobieness abstracted away. The main event here is `SqlMapping`. Differences with `DoobieMapping` are:
  - Implementations must explain how they deal with SQL and encoding of parameters and column values. This bit has been sliced off as `SqlModule` for readability.
  - `DoobieRoot` and friends are now `SqlRoot` and friends.
  - `ColumnRef` requires an explicit codec (`Meta` for doobie. `Codec` for Skunk).
  - `SqlLeafMapping` requires a codec as well.
  - `Subobject` is gone, just pass a sequence of `Join`s.
- `modules/skunk`, which defines `SkunkMapping` in terms of `SqlMapping` and replicates the existing doobie tests.
- `modules/doobie-2`, which defines a *new* `DoobieMapping` in terms of `SqlMapping`  and replicates the existing doobie tests.

Note that the existing `modules/doobie` is unchanged so as not to break existing users (i.e., Miles).

Remaining

- [x] discussion, as needed
- [x] deduplicate the tests

### CODE REVIEW

**Comment by tpolecat** [comment]
Closing for now, I want to see if I can minimize this.

**Comment by tpolecat** [comment]
# Don't merge yet but I want this open to see CI status

**Comment by tpolecat** [comment]
Ok @milessabin see what you think about this.

**Comment by milessabin** [comment]
This looks great ... I'm keen to cut over to the new refactored doobie mapping ASAP.

**Review by milessabin — APPROVED** [review]

**Comment by tpolecat** [comment]
Ok I deduplicated the tests, so now we can be sure we're running the exact same testcases against both Skunk and doobie. The new projects weren't actually being tested all this time because they weren't in the main project aggregate, oops. Fixed now. CI should take a bit longer as a result :-\

**Pull request merged**
