### PR TITLE
Bumped versions; fixed lint errors

### PR DESCRIPTION
**Pull request by milessabin**
Bumped all the versions and fixed the resulting glitches.

### CODE REVIEW

**Comment by milessabin** [comment]
Hmm ... that semanticdb dependency failure is odd. It looks like it should have been fixed in SBT 1.4.4.

**Comment by tpolecat** [comment]
I think we need to update `sbt-lucuma`, which is pulling in an old version of scalafix. For now try adding scalafix expliictly with the latest version.

**Comment by milessabin** [comment]
That appears to have done the trick ... thanks!

**Comment by tpolecat** [comment]
> Is there any reason why we can't point Scala Steward at Grackle?

no, we should do that. and set up mergify as well. feel free, or open an issue and one of us can do it

**Review by tpolecat — APPROVED** [review]

**Pull request merged**
