### PR TITLE
Don't special-case `0.0.0.0` in skunk suites

### PR DESCRIPTION
**Pull request by armanbilge**
Opening to see what CI does ...

### CODE REVIEW

**Comment by armanbilge** [comment]
Seems to be working fine in CI. @milessabin can you share more about the system where you needed this workaround?

**Comment by milessabin** [comment]
I'll try JDKs which match CI.

**Comment by armanbilge** [comment]
Hmm, ok, well now CI is failing 🤔

**Comment by armanbilge** [comment]
I re-ran CI for the original commit and now that one also fails 🤷 sorry 😅

**Comment by milessabin** [comment]
Simultaneously with you being able to trigger this in CI, I'm not currently able to reproduce the problem locally! :zany_face: 

This appears to be a very odd upstream (but which upstream?) bug, and I think we should just live with the workaround for now.

**Pull request closed without merging**
